name: "Publish npm"

on: push

jobs: 
      publish: 
      
              runs-on: ubuntu-latest
              steps: 
                  - name: checkout
                    uses: actions/checkout@v2
                  - name: node
                    uses: actions/setup-node@v2
                    with: 
                          node-version: 12
                          registry-url: https://registry.npmjs.org/
                  - name: build
                    run: |
                         npm install
                         npm run lint
                         npm run clean
                         npm run build
#                   - name: Authenticate with npm
#                     run: echo "https://registry.npmjs.org/:_authToken=\${{ secrets.NPM_TOKEN }}" > ~/.npmrc

                  - name: Install dependencies
                    run: npm ci

                  - name: publish
                    env:
                      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                    run: npm config set registry https://registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > ~/.npmrc |
                     npm publish --access public
