name: "Publish npm"

on: push

jobs: 
      publish: 
      
              runs-on: ubuntu-latest
              steps: 
                  - name: checkout
                    uses: actions/checkout@v2
                  - name: node
                    uses: actions/setup-node@v2
                    with: 
                          node-version: 18.16.0
                          registry-url: https://registry.npmjs.org
                  - name: build
                    run: pip3 install |
                         npm install knex
                         npm run build
                         npm run lint
                         npm run clean
                  - name: publish
                    env:
                      NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
                    run: |
                      echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
                      npm publish
